import {
  Layout,
  Type,
  CheckSquare,
  CircleDot,
  Calendar,
  Mail,
  Hash,
  FileText,
  Upload,
  Image as ImageIcon,
  Heading1,
  Heading2,
  List,
  ListOrdered,
  Quote,
  Smile,
  Code,
  Phone,
  Link as LinkIcon,
  MousePointer2,
  Star,
  BarChart,
  Layers,
  Table,
  Sliders,
  Fingerprint,
  Video,
  Music,
  MapPin,
  Minus,
  Columns,
  Calculator,
  Eye,
  Globe,
  ShieldCheck,
  FileCheck,
  CreditCard,
  User,
  HelpCircle,
  AlignLeft,
} from "lucide-react";

export const BLOCK_TYPES = [
  // --- Text & Headings ---
  {
    id: "text",
    label: "Text",
    icon: Type,
    group: "Basic",
    description: "Write plain text or instructions",
  },
  {
    id: "heading_1",
    label: "Heading 1",
    icon: Heading1,
    group: "Basic",
    description: "Large section heading",
  },
  {
    id: "heading_2",
    label: "Heading 2",
    icon: Heading2,
    group: "Basic",
    description: "Medium section heading",
  },
  {
    id: "heading_3",
    label: "Heading 3",
    icon: AlignLeft,
    group: "Basic",
    description: "Small section heading",
  },
  {
    id: "bullet_list",
    label: "Bullet List",
    icon: List,
    group: "Basic",
    description: "Simple bulleted list",
  },
  {
    id: "numbered_list",
    label: "Numbered List",
    icon: ListOrdered,
    group: "Basic",
    description: "Sequential numbered list",
  },
  {
    id: "quote",
    label: "Quote",
    icon: Quote,
    group: "Basic",
    description: "Capture a testimonial or quote",
  },
  {
    id: "callout",
    label: "Callout",
    icon: Smile,
    group: "Basic",
    description: "Highlight important info",
  },
  {
    id: "code_block",
    label: "Code",
    icon: Code,
    group: "Basic",
    description: "Share code snippets",
  },

  // --- Standard Inputs ---
  {
    id: "short_answer",
    label: "Short Answer",
    icon: Type,
    group: "Input",
    description: "Small text input",
  },
  {
    id: "long_answer",
    label: "Long Answer",
    icon: FileText,
    group: "Input",
    description: "Large text area",
  },
  {
    id: "multiple_choice",
    label: "Multiple Choice",
    icon: CircleDot,
    group: "Input",
    description: "Pick one option",
  },
  {
    id: "checkboxes",
    label: "Checkboxes",
    icon: CheckSquare,
    group: "Input",
    description: "Pick multiple options",
  },
  {
    id: "dropdown",
    label: "Dropdown",
    icon: List,
    group: "Input",
    description: "Select from a list",
  },
  {
    id: "email",
    label: "Email",
    icon: Mail,
    group: "Input",
    description: "Email address validation",
  },
  {
    id: "phone",
    label: "Phone Number",
    icon: Phone,
    group: "Input",
    description: "Contact number input",
  },
  {
    id: "number",
    label: "Number",
    icon: Hash,
    group: "Input",
    description: "Only numeric input",
  },
  {
    id: "url",
    label: "URL",
    icon: LinkIcon,
    group: "Input",
    description: "Website link validation",
  },
  {
    id: "date",
    label: "Date",
    icon: Calendar,
    group: "Input",
    description: "Date picker",
  },
  {
    id: "time",
    icon: MousePointer2,
    label: "Time",
    group: "Input",
    description: "Specific time selection",
  },

  // --- Advanced Inputs ---
  {
    id: "rating",
    label: "Rating",
    icon: Star,
    group: "Advanced",
    description: "Star or number rating",
  },
  {
    id: "opinion_scale",
    label: "Opinion Scale",
    icon: BarChart,
    group: "Advanced",
    description: "Scale from 0 to 10",
  },
  {
    id: "ranking",
    label: "Ranking",
    icon: Layers,
    group: "Advanced",
    description: "Order items by preference",
  },
  {
    id: "matrix",
    label: "Matrix",
    icon: Table,
    group: "Advanced",
    description: "Multiple choice grid",
  },
  {
    id: "slider",
    label: "Slider",
    icon: Sliders,
    group: "Advanced",
    description: "Range selection slider",
  },
  {
    id: "signature",
    label: "Signature",
    icon: Fingerprint,
    group: "Advanced",
    description: "Collect e-signatures",
  },
  {
    id: "file",
    label: "File Upload",
    icon: Upload,
    group: "Advanced",
    description: "Accept files from users",
  },

  // --- Media & Embeds ---
  {
    id: "image",
    label: "Image",
    icon: ImageIcon,
    group: "Media",
    description: "Upload or link an image",
  },
  {
    id: "video",
    label: "Video",
    icon: Video,
    group: "Media",
    description: "Embed YouTube/Vimeo",
  },
  {
    id: "audio",
    label: "Audio",
    icon: Music,
    group: "Media",
    description: "Embed Spotify/Soundcloud",
  },
  {
    id: "google_maps",
    label: "Google Maps",
    icon: MapPin,
    group: "Media",
    description: "Embed a location",
  },

  // --- Layout & Logic ---
  {
    id: "divider",
    label: "Divider",
    icon: Minus,
    group: "Layout",
    description: "Visual horizontal line",
  },
  {
    id: "spacer",
    label: "Spacer",
    icon: Layout,
    group: "Layout",
    description: "Empty vertical space",
  },
  {
    id: "columns_2",
    label: "2 Columns",
    icon: Columns,
    group: "Layout",
    description: "Side-by-side blocks",
  },
  {
    id: "calculator",
    label: "Calculator",
    icon: Calculator,
    group: "Logic",
    description: "Perform math on inputs",
  },
  {
    id: "hidden_field",
    label: "Hidden Field",
    icon: Eye,
    group: "Logic",
    description: "Store invisible metadata",
  },

  // --- Specialized & Legal ---
  {
    id: "address",
    label: "Address",
    icon: MapPin,
    group: "Special",
    description: "Structured address input",
  },
  {
    id: "country",
    label: "Country",
    icon: Globe,
    group: "Special",
    description: "Country selector",
  },
  {
    id: "gdpr",
    label: "GDPR Consent",
    icon: ShieldCheck,
    group: "Special",
    description: "Legal compliance checkbox",
  },
  {
    id: "terms",
    label: "Terms & Conditions",
    icon: FileCheck,
    group: "Special",
    description: "Link and accept terms",
  },
  {
    id: "payment",
    label: "Stripe Payment",
    icon: CreditCard,
    group: "Special",
    description: "Collect payments",
  },
  {
    id: "captcha",
    label: "CAPTCHA",
    icon: User,
    group: "Special",
    description: "Prevent spam bots",
  },
  {
    id: "help_text",
    label: "Help Text",
    icon: HelpCircle,
    group: "Special",
    description: "Tooltips and guides",
  },
];

export const INITIAL_BLOCKS = [
  { id: "b1", type: "text", content: "Event Registration", isTitle: true },
  {
    id: "b2",
    type: "text",
    content: "Please fill out the details below to register for the event.",
  },
  {
    id: "b3_1",
    type: "short_answer",
    content: "First Name",
    placeholder: "Your first name",
    required: true,
    system: true,
  },
  {
    id: "b3_2",
    type: "short_answer",
    content: "Last Name",
    placeholder: "Your last name",
    required: true,
    system: true,
  },
  {
    id: "b4",
    type: "email",
    content: "Email Address",
    placeholder: "Your email",
    required: true,
    system: true,
  },
];

export const FONTS = [
  { name: "Sans Serif", value: "font-sans" },
  { name: "Serif", value: "font-serif" },
  { name: "Mono", value: "font-mono" },
];

export const COLORS = [
  { name: "Teal", value: "teal", hex: "#14b8a6" },
  { name: "Blue", value: "blue", hex: "#3b82f6" },
  { name: "Purple", value: "purple", hex: "#a855f7" },
  { name: "Rose", value: "rose", hex: "#f43f5e" },
  { name: "Orange", value: "orange", hex: "#f97316" },
];